spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/ai_keep?useSSL=false&autoReconnect=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mhe020415..
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher  #解决swagger 3与Spring boot的版本兼容问题
  main:
    allow-bean-definition-overriding:
      true
#
## 开启mp的日志（输出到控制台）
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl